# Generated by Django 3.2.18 on 2025-03-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20250321_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_downvote_tip', 'Can downvote tip')]},
        ),
    ]
